### ISSUE TITLE
Warning (failure) when calculating version

### ISSUE THREAD

**Issue by tyleraland** [fhcrc/deenurp#55]
I install deenurp to a virtualenv (i.e., under the covers, deenurp is cloned to /tmp and pip executes `python setup.py install`).  Later, when I run a command (`deenurp ncbi_extract_genbank`) I get the following error:

```
WARNING version.py version 46 Command '['git', '-C', '/mnt/disk2/molmicro/venv/2.7.11/straintyping_pipeline-1-env/lib/python2.7/site-packages/deenurp-0.1.7-py2.7.egg/deenurp', 'describe', '--tags']' returned non-zero exit status 128
```

And, indeed, that .egg directory is NOT a git repository  Cloning https://github.com/fhcrc/deenurp.git (to v0.1.7) to /tmp/pip-build-inSxpH/deenurp

I think the issue here is that you've only tested this with the '--editable' flag, because when I use that, my problems go away.  However, I'd rather not have to install deenurp as editable.

**Comment by nhoffman** [comment]
Tyler,

Can you share relevant portions of your installation script so that I can try to reproduce the issue? In the meantime, your best bet is probably to create a tarball using ``python setup.py sdist`` from within the cloned repo and install from that.

Thanks,
Noah

**Comment by tyleraland** [comment]
I can't seem to reproduce the error anymore when installing to a new virtualenv, so maybe the initial installation failed somehow that first time and that failure produced weird behavior afterwards.

**Comment by tyleraland** [comment]
No error this time, but I do get a warning complaining that it can't run `git describe --tags`, because the directory isn't a git repository.  Curiously, the program does return the correct version anyway.  And the final return call is 0 (success) so this shouldn't affect behavior, it just spits out some concerning messages to stderr.

```
virtualenv test-env
source test-env/bin/activate
pip install biopython retrying
pip install git+https://github.com/fhcrc/deenurp.git@v0.1.7#egg=deenurp

deenurp --version
2016-05-24 09:30:57 WARNING version.py version 46 Command '['git', '-C', '/home/local/AMC/tland9/test-env/lib/python2.7/site-packages/deenurp', 'describe', '--tags']' returned non-zero exit status 128
2016-05-24 09:30:57 WARNING version.py version 46 Command '['git', 'describe', '--tags']' returned non-zero exit status 128
... (unrelated errors because optional dependencies for various subcommands aren't installed)
0.1.7

echo $?
0
```

**Comment by crosenth** [comment]
I have updated these messages to log.debug.  They will no longer be broadcast with default verbosity.
