### ISSUE TITLE
Add as collaborator?

### ISSUE THREAD

**Issue by sminot** [fhcrc/deenurp#59]
I've got a branch locally adding a Dockerfile. Could I be added to this repo / group so that I can put together a pull request for your review?

Thanks!

**Comment by nhoffman** [comment]
done - looking forward to using this! I should to write this down someplace, but we typically create an issue for a feature, and name a corresponding branch using the issue number (something like 059-add-collaborator). This makes it easier to keep track of what each feature branch was for. Thanks a lot for contributing!

**Comment by crosenth** [comment]
Thanks Noah
